import styles from "styles/components/footer.module.scss"

const Footer = ()=>{
    return(
        <>
            <footer className={styles.footer}>
                <div className={styles.gentext}>
                    Generated by &nbsp;
                    <button className={styles.sinsinpurinbutton}>
                    <a href="https://github.com/sinsinpurin" className={styles.sinsinpurinurl}>sinsinpurin</a>
                    </button>
                </div>
            </footer>
        </>
    )
}

export default Footer